import type { Metadata } from "next";
import "./globals.css";
import AppSidebar from "@/components/AppSidebar";
import ThemeProvider from "@/components/ThemeProvider";
import LanguageProvider from "@/hooks/useTranslation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <LanguageProvider>
          <ThemeProvider>
            <AppSidebar>{children}</AppSidebar>
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
